#!/bin/sh

set -e

# Install rbenv:
brew install rbenv

# Rubies:
rbenv install $RUBY_VERSION

# Update rubygems/bundler:
gem update --system
gem install bundler
gem install solargraph
gem install rufo
gem install ruby-debug-ide
gem install reek
gem install fasterer
gem install debride

solargraph download-core $RUBY_VERSION
