#!/bin/sh

set -e

ln -sf $DOT_DIR/docker/exec/node /usr/local/bin
ln -sf $DOT_DIR/docker/exec/yarn /usr/local/bin

docker create -it                                         \
              --init                                      \
              --name=node                                 \
              --restart=unless-stopped                    \
              --shm-size 512M                             \
              -v $HOME:$HOME                              \
              node:lts

docker start node
