#!/bin/sh

set -e

ln -sf $DOT_DIR/docker/exec/node /usr/local/bin
ln -sf $DOT_DIR/docker/exec/yarn /usr/local/bin

docker create -i                                          \
              --init                                      \
              --name=node                                 \
              --restart=unless-stopped                    \
              --shm-size 512M                             \
              -v $HOME:$HOME                              \
              -v $HOME/.cache/yarn:/home/node/.cache/yarn \
              node:lts-alpine

docker start node
