#!/bin/sh

set -e

docker create -it                               \
              --init                            \
              --name=selenium-standalone-chrome \
              --restart=no                      \
              --shm-size=2g                     \
              -p :$SELENIUM_PORT:$SELENIUM_PORT \
              selenium/standalone-chrome:4
