#!/bin/sh

set -e

# Setup env
./env/install

# Setup shell:
./zsh/install

# Setup terminal
./terminal/install

# Copy hosts file
sudo cp hosts/hosts /private/etc/hosts

# Install command line tools
xcode-select --install 2>&1

# Install homebrew:
./homebrew/install

# Install git:
./git/install

# Install rubies
./ruby/install

# Install docker
#./docker/install

# Install fonts:
#./fonts/install

# Install vscode
#./vscode/install

cp ./launchd/set_audio_output.plist ~/Library/LaunchAgents/local.ab_local.set_audio_output.plist
launchctl load ~/Library/LaunchAgents/local.ab_local.set_audio_output.plist
