version: "3.4"

services:
  nginx:
    image: "nginx-self-signed:stable-alpine"
    container_name: ${PROJECT}_nginx-self-signed
    build:
      context: ./
      target: nginx
    volumes:
      - type: bind
        source: ./etc/config/nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "80:80"
      - "443:443"

  mysql:
    image: "mysql:latest"
    container_name: ${PROJECT}_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${PROJECT_GROUP}
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
    name: ${PROJECT_GROUP}-mysql
    external: true
