version: "3.4"

services:
  mysql:
    environment:
      - MYSQL_DATABASE=${PROJECT_GROUP}_test
    volumes: []

  selenium:
    image: "selenium/standalone-chrome:latest"
    shm_size: 2g
    ports:
      - "4444:4444"
