#!/bin/sh

/bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

# Install default formulae
brew install coreutils
brew install pstree
brew install zlib

# Install dflfantasy specific formulae
#brew install librsvg2
#brew install gobject-introspection

# Install sdquiz specific formulae
#brew install v8@3.15

# Install sddrive specific formulae
#brew install ffmpeg
