#!/bin/sh

set -e

curl -sSL https://rvm.io/mpapis.asc | gpg --import -
gpg --recv-keys
gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
\curl -sSL https://get.rvm.io | bash -s stable --autolibs=homebrew --ignore-dotfiles

ln -sf $DOT_DIR/rvm/gemsets/default.gems $HOME/.rvm/gemsets/default.gems # overwritten by rvm installation
ln -sf $DOT_DIR/rvm/gemsets/global.gems $HOME/.rvm/gemsets/global.gems # overwritten by rvm installation

source ~/.rvm/scripts/rvm
rvm autolibs enable
rvm reload
