#!/bin/sh

function code_clean {
  code --disable-extensions --new-window $@
}

function code_project {
  project_dir=$(find $DEVEL_DIR -maxdepth 2 -type d -name $1 -print)
  workspace_file=$DOT_DIR/vscode/workspaces/$1.code-workspace

  cd $project_dir
  code $workspace_file --new-window
}

alias c=code
alias cc=code_clean
alias project=code_project
alias p=code_project
